# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: Gruvbox
email: brisvag@gmail.com
full_name: Lorenzo Gaifas
github_repository_url: https://github.com/brisvag/napari-gruvbox
github_username_or_organization: brisvag
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: false
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: GNU GPL v3.0
module_name: napari_gruvbox
plugin_name: napari-gruvbox
short_description: Gruvbox theme for napari.
